#!/usr/bin/env bash

set -euo pipefail

print_usage() {
	echo "Usage: ${0} --user <user_name> --host <host_name>"
}

user=""
host=""

while [[ $# -gt 0 ]]; do
	case "$1" in
	--user)
		user="${2}"
		shift 2
		;;
	--host)
		host="${2}"
		shift 2
		;;
	-h | --help)
		print_usage
		exit 0
		;;
	*)
		print_usage >&2
		exit 1
		;;
	esac
done

if [[ -z "${user}" || -z "${host}" ]]; then
	print_usage >&2
	exit 1
fi

pub_key_file="$(find "${HOME}/.ssh/" -name "*.pub" | fzf)"

ssh "${user}@${host}" \
	'mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys && chmod 700 ~/.ssh/authorized_keys' \
	<"${pub_key_file}"
