#!/usr/bin/env fish

while read --nchars 1 -l response \
    --prompt-str="Are you sure that you want to delete the remote branch? (y/n)"
      or return 1 # if the read was aborted with ctrl-c/ctrl-d
    switch $response
        case y Y
            git push origin --delete (git branch --show-current)
            git branch --unset-upstream
            return 0
        case n N
            echo "Doing nothing"
            return 0
        case '*'
            echo "Please type y or n"
            continue
    end
end
