#!/usr/bin/env bash

set -euo pipefail

usage() {
    echo "Usage: repatriate_window [-a]"
    echo "Handles focused window by default; handles all windows if the -a switch is provided"
}

all=false

while getopts 'a' opt; do
    case "${opt}" in
        a) all=true ;;
        *) usage >&2; exit 1;;
    esac
done

windows=()

if $all; then
    readarray -t windows < <(aerospace list-windows --all --format "%{app-name},%{window-id}")
else
    readarray -t windows < <(aerospace list-windows --focused --format "%{app-name},%{window-id}")
fi

for window in "${windows[@]}"; do
    IFS=',' read -ra app_name_and_window_id <<< "$window"
    app_name="${app_name_and_window_id[0]}"
    window_id="${app_name_and_window_id[1]}"
    case "$app_name" in
        WezTerm)
            aerospace move-node-to-workspace "$window_id" 1 ;;
        "Google Chrome")
            aerospace move-node-to-workspace "$window_id" 2 ;;
        Obsidian)
            aerospace move-node-to-workspace "$window_id" 3 ;;
        Zathura)
            aerospace move-node-to-workspace "$window_id" 4 ;;
        *)
            aerospace move-node-to-workspace "$window_id" 5 ;;
    esac
done
