#!/usr/bin/env bash

set -euo pipefail

usage() {
    echo "Usage: repatriate_windows [-a]"
    echo "-a    Send every window with a default workspace to its default workspace"
    echo "      If omitted, only the currently focused window is sent to its defauls workspace, if it has one."
}

all=false

while getopts 'a' opt; do
    case "${opt}" in
        a) all=true ;;
        *) usage >&2; exit 1;;
    esac
done

windows=()

if $all; then
    readarray -t windows < <(aerospace list-windows --all --format "%{app-name},%{window-id}")
else
    readarray -t windows < <(aerospace list-windows --focused --format "%{app-name},%{window-id}")
fi

for window in "${windows[@]}"; do
    IFS=',' read -ra app_name_and_window_id <<< "$window"
    app_name="${app_name_and_window_id[0]}"
    window_id="${app_name_and_window_id[1]}"
    case "$app_name" in
        WezTerm)
            aerospace move-node-to-workspace --window-id "$window_id" 1 2>/dev/null ;;
        "Google Chrome")
            aerospace move-node-to-workspace --window-id "$window_id" 2 2>/dev/null ;;
        Obsidian)
            aerospace move-node-to-workspace --window-id "$window_id" 3 2>/dev/null ;;
        Zathura)
            aerospace move-node-to-workspace --window-id "$window_id" 4 2>/dev/null ;;
        *)
            aerospace move-node-to-workspace --window-id "$window_id" 5 2>/dev/null ;;
    esac
done
