#!/usr/bin/bash

# Usage: <script> <.txt file from which to restore session>
# Exampe usage: <script> ~/my-fave-tmux-session.txt

unlink ~/.local/share/tmux/resurrect/last 
ln -s `realpath $1` ~/.local/share/tmux/resurrect/last

