#!/usr/bin/env bash

bail() {
	echo "${1}"
	exit 1
}

os=""
case "$(uname -s)" in
Darwin)
	os=macos
	;;
Linux)
	if [[ -f /etc/os-release ]]; then
		source /etc/os-release
		case "$ID" in
		debian)
			os=debianlike
			;;
		ubuntu)
			os=debianlike
			;;
		arch)
			os=arch
			;;
		*)
			bail "Unrecognised Linux Distro"
			;;
		esac
	else
		bail "Unrecognised Linux distro"
	fi
	;;
*)
	bail "Unrecognised OS"
	;;
esac

[[ -z "${os+x}" ]] && bail "Unrecognised OS"
[[ "${os}" == debianlike ]] && sudo apt-get update -y
if [[ "${os}" == macos ]]; then
	brew_install_script
	brew_install_script=$(mktemp)
    if curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh >"${brew_install_script}"; then
		/bin/sh "${brew_install_script}"
	else
		bail "Failed to install homebrew"
	fi
	unset brew_install_script
fi

install_rust_toolchain_and_cargo_binstall() {
	local rustup_install_script
	rustup_install_script=$(mktemp)
	if curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs >"${rustup_install_script}"; then
	    sh "${rustup_install_script}" -y
	else
		bail "Faile to install rustup"
	fi
	local cargo_binstall_install_script
	cargo_binstall_install_script=$(mktemp)
	if curl -L --proto '=https' --tlsv1.2 -sSf \
		https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh \
		>"${cargo_binstall_install_script}"; then
		bash "${cargo_binstall_install_script}"
	else
		bail "Failed to install cargo-binstall"
	fi
}

install_rust_toolchain_and_cargo_binstall
cargo install cargo-shuttle
cargo install cargo-update
cargo install sccache
cargo install tokio-console
cargo install tree-sitter-cli

install_macos_only_stuff() {
	brew install gh # Installing on linux is not straightforward and is best done manually
	brew install --cask aerospace
	brew install --cask font-fira-code
}
install_macos_only_stuff

install_linux_only_stuff() {
	sudo pacman -Syu nerd-fonts-fira-code
}

install() {
	local is_gui=false
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --gui)
                is_gui=true
                shift
                ;;
            --) # end of options
                shift
                break # break out of while loop
                ;;
            *)  # anything else, stop processing
                break # break out of while loop
                ;;
        esac
    done
	[[ $# -ne 1 ]] && echo "Usage: install [--gui] package_name"
	[[ $# -ne 1 ]] && exit 1
	local package="${1}"
	case "${os}" in
	macos)
		if "${is_gui}"; then
			brew install --cask "${package}"
		else
			brew install "${package}"
		fi
		;;
	debianlike)
		sudo apt-get install -y "${package}"
		;;
	arch)
		sudo pacman -Syu --noconfirm "${package}"
		;;
	esac
}

install --gui wezterm
install --gui chrome
install bash
install bat
install broot
install cloc
install eza
install fd
install fish
install flamegraph
install fzf
install git
install gitleaks
install grep
install ncdu
install neovim
install node
install pandoc
install parallel
install ripgrep
install sd
install shellcheck
install shfmt
install sponge
install starship
install stow
install tldr
install tmux
install yazi
install zoxide
install zsh

npm install jquery
