#! /usr/bin/env fish

# stash the current changes without changing the files back to their HEAD state

set -l message ""

if test (count $argv) -gt 0
    mesage = $argv[1]
end

git stash store -m $message (git stash create)
