#!/usr/bin/env python3

import json
import sys
import os

if len(sys.argv) != 2:
    print(f"Usage: tmux_init <json_file_specifying_tmux_sessions_and_windows>")
    sys.exit(1)

with open(sys.argv[1], 'r') as f:
    data = json.load(f)

first_session = ""

for entry in data:
    session = entry.get("session", "")
    assert session
    if not first_session:
        first_session = session
    window_dirs = entry["window_dirs_and_titles"]
    assert window_dirs
    first_dir, first_title = window_dirs[0]
    os.system(f"tmux new-session -d -s {session} -c {first_dir}")
    if first_title:
        os.system(f"tmux rename-window -t {session}:0 -n {first_title}")
    for dir, title in window_dirs[1:]:
        title_specifier = ""
        if title:
            title_specifier = f" -n {title}"
        os.system(f"tmux new-window -t {session}: -c {dir}{title_specifier}")
    os.system(f"tmux select-window -t {session}:0")

os.system(f"tmux attach -t {first_session}")

# Example json file specifying tmux sessions and windows
# [
#   {
#     "session": "dotfiles",
#     "window_dirs_and_titles": [["$HOME/dotfiles", ""], ["$HOME/dotfiles", ""], ["$HOME/dotfiles", "build"]]
#   },
#   {
#     "session": "scripts",
#     "window_dirs_and_titles": [["$HOME/dev/scripts", ""], ["$HOME/dev/scripts", ""], ["$HOME/dev/scripts", "build"]]
#   }
# ]
