#!/usr/bin/env bash

# Unsetting RUSTC_WRAPPER just while we do the initial cargo installs
unset RUSTC_WRAPPER
install_rust_toolchain_and_sccache_and_cargo_binstall() {
	local rustup_install_script
	rustup_install_script=$(mktemp)
	if curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs >"${rustup_install_script}"; then
		sh "${rustup_install_script}" -y || bail "Failed to install rustup"
	else
		bail "Failed to install rustup"
	fi
	# Installing sccache here because cargo-binstall needs it
	cargo install sccache
	local cargo_binstall_install_script
	cargo_binstall_install_script=$(mktemp)
	if curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh >"${cargo_binstall_install_script}"; then
		bash "${cargo_binstall_install_script}" || bail "Failed to install cargo-binstall"
	else
		bail "Failed to install cargo-binstall"
	fi
}
install_rust_toolchain_and_sccache_and_cargo_binstall
cargo install broot
cargo install cargo-shuttle
cargo install cargo-update
cargo install fd-find
cargo install flamegraph
cargo install starship
cargo install tokio-console
cargo install --force yazi-build
