#!/usr/bin/env bash

package="$1"

case "$(uname -s)" in
Darwin)
	brew search "/^${package}$/" >/dev/null 2>&1
	;;
Linux)
	if [[ -f /etc/os-release ]]; then
		os_release_file="/etc/os-release"
		if grep -iq "arch" "${os_release_file}"; then
			pacman -Ss "^${package}$" >/dev/null 2>&1
		fi
	else
		echo "Unrecognised Linux distro"
		exit 1
	fi
	;;
*)
	echo "Unrecognised OS"
	exit 1
	;;
esac
