#!/usr/bin/env bash

bail() {
	echo "$1"
	exit 1
}

package="$1"

case "$(uname -s)" in
Darwin)
	brew search "/^${package}$/" >/dev/null 2>&1
	;;
Linux)
	if [[ -f /etc/os-release ]]; then
		os_release_file="/etc/os-release"
		if grep -iq '^ID=fedora$' "${os_release_file}"; then
			dnf list available "^${package}$" >/dev/null 2>&1
		else
			bail "Unrecognised linux distro"
		fi
	else
		bail "Unrecognised Linux distro"
	fi
	;;
*)
	bail "Unrecognised OS"
	;;
esac
