#!/usr/bin/env bash

# Do not run with sudo - you will be prompted for sudo the first time it is needed and then it
# will remain valid for a few minutes while the rest of the installation proceeds

set -euo pipefail

bail() {
	echo "${1}"
	exit 1
}

os=""
case "$(uname -s)" in
Darwin)
	os=macos
	;;
Linux)
	if [[ -f /etc/os-release ]]; then
		os_release_file="/etc/os-release"
		if grep -iq '^ID=fedora$' "${os_release_file}"; then
			os=fedora
		fi
	else
		bail "Unrecognised Linux distro"
	fi
	;;
*)
	bail "Unrecognised OS"
	;;
esac

if [[ -z "${os+x}" ]]; then
	bail "Unrecognised OS"
fi
if [[ "${os}" == macos ]]; then
	brew_install_script=$(mktemp)
	if curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh >"${brew_install_script}"; then
		/bin/sh "${brew_install_script}"
	else
		bail "Failed to install homebrew"
	fi
	unset brew_install_script
fi

the_user=''
setup_user() {
	if [[ "${os}" == fedora ]]; then
		while [[ -z "$the_user" ]]; do
			echo "Please enter the name of the user you wish to set up"
			read -r the_user
		done
		if ! id -u "${the_user}" >/dev/null 2>&1; then
			sudo useradd -m -G wheel -s /bin/bash "${the_user}"
			sudo passwd "${the_user}"
		fi
		echo "Logging in as ${the_user}"
		su - "${the_user}"
	fi
}
setup_user

setup_ssh() {
	if [[ ! -e "${HOME}/.ssh/id_ed25519.pub" ]]; then
		email_address=''
		while [[ -z "${email_address}" ]]; do
			echo "Please enter your email for your new ssh key:"
			read -r email_address
		done
		ssh-keygen -t ed25519 -C "${email_address}"
		echo "Add this key to github now; press any key to continue when you are done"
		cat "${HOME}/.ssh/id_ed25519.pub"
		read -n 1 -s -r
		echo
	fi
}
setup_ssh
