#!/usr/bin/env bash

# Do not run with sudo - you will be prompted for sudo the first time it is needed and then it
# will remain valid for a few minutes while the rest of the installation proceeds

set -euo pipefail

bail() {
	echo "${1}"
	exit 1
}

case "$(uname -s)" in
Darwin) ;;
Linux)
	the_user=''
	while [[ -z "$the_user" ]]; do
		echo "Please enter the name of the user you wish to set up"
		read -r the_user </dev/tty
	done
	if ! id -u "${the_user}" >/dev/null 2>&1; then
		sudo useradd -m -G wheel -s /bin/bash "${the_user}"
		sudo passwd "${the_user}"
	fi
	echo
	echo "Now please login as ${the_user} with the command \"su - ${the_user}\""
	;;
*)
	bail "Unrecognised OS"
	;;
esac
