#!/usr/bin/env bash

if [[ "$#" -ne 1 ]]; then
	echo "Usage: setup_ssh email"
	exit 1
fi

ssh-keygen -t ed25519 -C "${1}"
echo "You may want to add this key to github now:"
cat "${HOME}/.ssh/id_ed25519.pub"
