#! /usr/bin/env bash

set -euo pipefail

cargo check --workspace --all-targets --all-features
cargo clippy --workspace --all-targets --all-features
cargo fmt --check # Already covers the whole workspace with all targets and all features
