#!/usr/bin/env bash

usage() {
    echo "Usage gh_clone -o|--owner <owner> -r|--repos <repo_name_regex>"
    echo "Names will be matched case sensitively"
}

owner=""
repo_regex=""

while [[ $# -gt 0 ]]; do
    case "$1" in
    -o | --owner)
        owner="${2}"
        shift 2
        ;;
    -r | --repos)
        repo_regex="${2}"
        shift 2
        ;;
    -h | --help)
        usage
        exit 0
        ;;
    *)
        usage >&2
        exit 1
        ;;
    esac
done

if [[ -z "${owner}" || -z "${repo_regex}" ]]; then
    usage >&2
    exit 1
fi

readarray -t repos < <(gh repo list "${owner}" --limit 1000 | awk '{print $1}')

for repo in "${repos[@]}"; do
    repo_name="${repo##*/}"
    if [[ ! "${repo_name}" =~ $repo_regex ]]; then
        continue
    fi
    if [[ -d "${repo_name}" ]]; then
        echo "Directory ${repo_name} already exists" >&2
        continue
    fi
    echo "Cloning repo ${repo} ..." >&2
    gh repo clone "${repo}"
    echo "Finished cloning repo ${repo}" >&2
    for _ in {0..3}; do
        echo >&2
    done
done
