#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: tmux_go SESSION_NAME" >&2
    exit 1
fi

session="${1}"

if tmux has-session -t "${session}" &>/dev/null; then
    tmux select-window -t "${session}":1 &>/dev/null && tmux switch-client -t "${session}" &>/dev/null
fi
