#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: tmux_go SESSION_INDEX" >&2
    exit 1
fi

index="${1}"
mapfile -t sessions < <(tmux list-sessions -F "#{session_name}")
session="${sessions[$index]}"
if tmux has-session -t "${session}" &>/dev/null; then
    tmux select-window -t "${session}":1 &>/dev/null && tmux switch-client -t "${session}" &>/dev/null
fi
